CREATE TABLE IF NOT EXISTS clientes (
                                        id INTEGER PRIMARY KEY,
                                        nome TEXT NOT NULL,
                                        email TEXT UNIQUE NOT NULL
);

INSERT INTO clientes (id, nome, email) VALUES (1, 'José Pedro Machado', 'cliente_0_ester78@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (2, 'Maria Isis Siqueira', 'cliente_1_pedro72@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (3, 'Diego Ribeiro', 'cliente_2_fteixeira@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (4, 'Olívia Azevedo', 'cliente_3_ecampos@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (5, 'Diego Montenegro', 'cliente_4_ivasconcelos@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (6, 'Gustavo Viana', 'cliente_5_carvalhomaria-vitoria@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (7, 'Raul Pires', 'cliente_6_brunomendonca@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (8, 'Matheus Porto', 'cliente_7_luiz-fernandodas-neves@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (9, 'Maria Júlia Fogaça', 'cliente_8_tjesus@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (10, 'Ágatha Borges', 'cliente_9_nsousa@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (11, 'Josué Peixoto', 'cliente_10_msales@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (12, 'Ana Vitória da Rosa', 'cliente_11_diogo60@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (13, 'Eloá Vargas', 'cliente_12_lizaraujo@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (14, 'Daniela Moreira', 'cliente_13_imendes@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (15, 'Luiz Gustavo Rodrigues', 'cliente_14_albuquerqueheitor@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (16, 'Dr. Vitor Hugo Sousa', 'cliente_15_joaquimcamara@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (17, 'Dr. Augusto Moura', 'cliente_16_urezende@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (18, 'Vicente Campos', 'cliente_17_qfogaca@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (19, 'Enzo Garcia', 'cliente_18_juannogueira@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (20, 'Dr. Isaque Cavalcanti', 'cliente_19_pedro-miguel92@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (21, 'Maria Clara Pastor', 'cliente_20_luiz-henrique62@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (22, 'Marcelo Borges', 'cliente_21_oferreira@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (23, 'Dr. Arthur Siqueira', 'cliente_22_ffarias@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (24, 'Alana Lopes', 'cliente_23_dante33@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (25, 'Catarina Araújo', 'cliente_24_emoraes@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (26, 'Theo Borges', 'cliente_25_emanuellycaldeira@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (27, 'Larissa Farias', 'cliente_26_maria-sophiasantos@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (28, 'Ravy Costela', 'cliente_27_xrodrigues@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (29, 'Rebeca da Conceição', 'cliente_28_alexandreaparecida@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (30, 'Matheus Pastor', 'cliente_29_daniela44@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (31, 'Sarah Leão', 'cliente_30_cavalcanteeloah@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (32, 'Esther Pereira', 'cliente_31_raquelnunes@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (33, 'Zoe Gonçalves', 'cliente_32_siqueirayan@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (34, 'Emilly Vieira', 'cliente_33_flima@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (35, 'Calebe Cavalcante', 'cliente_34_allanacassiano@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (36, 'Luiza Duarte', 'cliente_35_ydas-neves@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (37, 'Mirella Oliveira', 'cliente_36_correiaalana@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (38, 'Bruno Pinto', 'cliente_37_rebeca69@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (39, 'Aylla Sampaio', 'cliente_38_rodriguessophie@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (40, 'Vitor Hugo Teixeira', 'cliente_39_cunhajosue@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (41, 'Marcela Lopes', 'cliente_40_vasconceloserick@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (42, 'Sra. Sara Rezende', 'cliente_41_mathias07@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (43, 'Srta. Ana Cecília Camargo', 'cliente_42_hjesus@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (44, 'Milena Costa', 'cliente_43_marquesana-carolina@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (45, 'Nicole Siqueira', 'cliente_44_almeidaaurora@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (46, 'Ana Liz Aragão', 'cliente_45_vasconceloserick@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (47, 'Gael Moura', 'cliente_46_belladuarte@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (48, 'Noah Martins', 'cliente_47_gustavo-henrique85@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (49, 'José Miguel Rios', 'cliente_48_ogarcia@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (50, 'Dra. Ana Sales', 'cliente_49_barbosaana-sophia@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (51, 'Joana Rios', 'cliente_50_rodrigomendes@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (52, 'Arthur Andrade', 'cliente_51_aurorasantos@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (53, 'Alícia Nunes', 'cliente_52_josue23@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (54, 'Fernanda Teixeira', 'cliente_53_araujoana-livia@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (55, 'Sra. Allana da Costa', 'cliente_54_carlos-eduardocosta@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (56, 'Maria Helena Nascimento', 'cliente_55_laragao@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (57, 'Dra. Carolina Siqueira', 'cliente_56_cardosorael@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (58, 'Caroline Ribeiro', 'cliente_57_pmoreira@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (59, 'Ian da Costa', 'cliente_58_raulbarbosa@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (60, 'Larissa da Paz', 'cliente_59_giovannacavalcante@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (61, 'Luna Cunha', 'cliente_60_vda-luz@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (62, 'Mariane Casa Grande', 'cliente_61_kevin51@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (63, 'Rodrigo Dias', 'cliente_62_qlima@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (64, 'Miguel Fonseca', 'cliente_63_joao-vitor33@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (65, 'Ana Carolina Machado', 'cliente_64_mendesguilherme@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (66, 'Marcelo Pimenta', 'cliente_65_dfonseca@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (67, 'Sr. Bernardo Nunes', 'cliente_66_davi-miguel42@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (68, 'Gael Pimenta', 'cliente_67_mendesnicolas@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (69, 'Augusto Araújo', 'cliente_68_maria-eduardaporto@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (70, 'Anthony Montenegro', 'cliente_69_da-rosastella@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (71, 'Sr. Benício Rodrigues', 'cliente_70_maria-juliada-paz@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (72, 'Ana Julia Oliveira', 'cliente_71_marcelaaragao@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (73, 'Ana Vitória Alves', 'cliente_72_qcostela@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (74, 'João Felipe Jesus', 'cliente_73_da-rosajuan@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (75, 'Sra. Emilly Silveira', 'cliente_74_juan60@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (76, 'Elisa Rios', 'cliente_75_pimentaguilherme@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (77, 'Dr. Vinícius Sá', 'cliente_76_falmeida@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (78, 'Beatriz Câmara', 'cliente_77_fernandesmaria-flor@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (79, 'Julia Almeida', 'cliente_78_nicolasnascimento@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (80, 'Sr. Eduardo Rios', 'cliente_79_nda-conceicao@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (81, 'Luara Moreira', 'cliente_80_ana65@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (82, 'Elisa Pinto', 'cliente_81_ayllamelo@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (83, 'Dr. Antônio Macedo', 'cliente_82_juliaandrade@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (84, 'Anthony Gabriel da Rocha', 'cliente_83_antonellarocha@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (85, 'Gael Henrique Andrade', 'cliente_84_barrosdom@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (86, 'Benício Sampaio', 'cliente_85_kevin92@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (87, 'Sophie Cunha', 'cliente_86_ester64@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (88, 'Dr. Antônio Novaes', 'cliente_87_udas-neves@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (89, 'Sr. Brayan da Luz', 'cliente_88_matteoda-cruz@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (90, 'Ravi Freitas', 'cliente_89_vmachado@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (91, 'Sra. Maya Abreu', 'cliente_90_joao-gabriel88@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (92, 'Srta. Luiza Leão', 'cliente_91_julia64@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (93, 'Ana Laura Castro', 'cliente_92_silvaeloah@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (94, 'Ana Liz Santos', 'cliente_93_heloisamachado@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (95, 'Dom Sá', 'cliente_94_ana-beatriz97@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (96, 'Gabriel Cardoso', 'cliente_95_fogacamiguel@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (97, 'André Araújo', 'cliente_96_gustavocastro@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (98, 'Benício Rocha', 'cliente_97_kgarcia@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (99, 'Sr. Paulo Nogueira', 'cliente_98_macedorenan@exemplo.com');
INSERT INTO clientes (id, nome, email) VALUES (100, 'Sara Silva', 'cliente_99_lopestheo@exemplo.com');
